---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: http://deb.kamailio.org/kamailiodebkey.gpg
    state: present

- name: add kamilio deb repository
  apt_repository:
    repo: deb http://deb.kamailio.org/kamailio52 stretch main
    state: present

- name: add kamail deb-src repository
  apt_repository:
    repo: deb-src http://deb.kamailio.org/kamailio52 stretch main
    state: present

- name: install kamailio
  apt: name={{item}} state=present update_cache=yes install_recommends=no
  with_items:
    - kamailio
